## Sign Up

POST http://localhost:3000/signup
Content-Type: application/json

{
    "id":"aaaaa00000",
    "pw": "1234567890",
    "username":"lee"
}


## login
POST http://localhost:3000/login
Content-Type: application/json

{
    id:"jaksdkfljaslkdf",
    pw: "1234"
}